-- Java ITS hosted user/progress storage for Supabase Postgres.
-- Run this once in Supabase SQL Editor.

create table if not exists public.java_its_users (
    id bigint generated by default as identity primary key,
    username text not null,
    username_key text not null unique,
    email text,
    email_key text unique,
    display_name text not null,
    password_salt text not null,
    password_hash text not null,
    created_at timestamptz not null default now(),
    last_login_at timestamptz
);

create table if not exists public.java_its_user_progress (
    user_id bigint primary key references public.java_its_users(id) on delete cascade,
    progress_json jsonb not null,
    updated_at timestamptz not null default now()
);

create index if not exists java_its_user_progress_updated_idx
    on public.java_its_user_progress (updated_at desc);

-- These tables are accessed only by the Streamlit server using the service-role
-- key stored in Streamlit secrets. Do not expose the service-role key in browser
-- JavaScript or public files.
-- Keeping RLS enabled is okay because service-role bypasses RLS, but direct anon
-- access remains blocked.
alter table public.java_its_users enable row level security;
alter table public.java_its_user_progress enable row level security;
